elka/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('reg.urls')),
    path('', include('event.urls')),
    path('feedback/', include('feedback.urls')),
    path('adminchat/', include('adminchat.urls')),
    path('partners/', include('partners.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

partners/urls.py
from django.urls import path
from . import views

app_name = 'partners'

urlpatterns = [
    path('new/', views.create_partner, name='new_partner'),
    path('', views.partners, name='partners'),
    path('info/<int:pk>/', views.info_partner, name='info_partner'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('edit/<int:pk>/', views.edit, name='edit_partner')
]

reg/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'reg'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='reg/login.html', authentication_form=LoginForm),
         name='login'),
    path('logout/', views.logout_view, name='logout')
]

partners/models.py
from django.db import models


class Partners(models.Model):
    name = models.CharField(max_length=255, verbose_name="Название партнёра")
    description = models.TextField(verbose_name="Описание", blank=True, null=True)
    main_image = models.ImageField(upload_to='partners_main_images/', verbose_name="Основное изображение", null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Партнёр"
        verbose_name_plural = "Партнёры"


class PartnersImage(models.Model):
    product = models.ForeignKey(Partners, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='product_images/', verbose_name="Дополнительное изображение")

    def __str__(self):
        return f"Дополнительное изображение для {self.product.name}"

    class Meta:
        verbose_name = "Дополнительное изображение партенра"
        verbose_name_plural = "Дополнительные изображения партнеров"

partners/forms.py
from django import forms
from django.forms import inlineformset_factory
from .models import Partners, PartnersImage


class PartnersForm(forms.ModelForm):
    class Meta:
        model = Partners
        fields = ['name', 'description', 'main_image']


PartnersImageFormSet = inlineformset_factory(
    Partners,
    PartnersImage,
    fields=('image',),
    extra=5,
    can_delete=True,
    max_num=100,
)

partners/views.py
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PartnersForm, PartnersImageFormSet
from .models import Partners, PartnersImage


def create_partner(request):
    if request.method == 'POST':
        form = PartnersForm(request.POST, request.FILES)
        formset = PartnersImageFormSet(request.POST, request.FILES, instance=Partners())
        if form.is_valid() and formset.is_valid():
            product = form.save()
            formset.instance = product
            formset.save()
            return redirect('/')
    else:
        form = PartnersForm()
        formset = PartnersImageFormSet(instance=Partners())

    return render(request, 'partners/create_partners.html', {'form': form, 'formset': formset})


def partners(request):
    partners = Partners.objects.all()

    return render(request, 'partners/partners.html', {'partners': partners})


def info_partner(request, pk):
    partner = get_object_or_404(Partners, pk=pk)
    images = PartnersImage.objects.filter(product=partner)

    return render(request, 'partners/detail_partner.html', context={'partner': partner, 'images': images})


@user_passes_test(lambda u: u.is_superuser)
def delete(request, pk):
    event = get_object_or_404(Partners, pk=pk)
    event.delete()

    return redirect('/')


@user_passes_test(lambda u: u.is_superuser)
def edit(request, pk):
    partner = get_object_or_404(Partners, pk=pk)
    if request.method == 'POST':
        form = PartnersForm(request.POST, request.FILES, instance=partner)
        formset = PartnersImageFormSet(request.POST, request.FILES, instance=partner)
        if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()

            return redirect('/')

    else:
        form = PartnersForm(instance=partner)
        formset = PartnersImageFormSet(instance=partner)

    return render(request, 'partners/edit_partners.html', context={'form': form, 'formset': formset})

partners/templates/partners/create_partners.html
{% extends 'reg/base.html' %}

{% block title %}Добавление партнера{% endblock %}

{% block content %}
    <h1>Создать товар</h1>

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}

        <div>
            {{ form.as_p }}
        </div>

        <h2>Дополнительные изображения товара</h2>
        {{ formset.management_form }}
        {% for image_form in formset %}
            <div>
                {{ image_form.as_p }}
            </div>
        {% endfor %}

        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

partners/templates/partners/detail_partner.html
{% extends 'reg/base.html' %}

{% block title %}Информация о партнере{% endblock %}

{% block content %}

<div>
    <div class="event">
        <div class="center-image">
            <img src="{{ partner.main_image.url }}">
        </div>

        <span>
            <p>{{ partner.name }}</p>
            <p>{{ partner.description }}</p>
        </span>
    </div>
    {% if user.is_superuser %}
        <a href="{% url 'partners:delete' partner.pk %}">Удалить</a>
        <a href="{% url 'partners:edit_partner' partner.pk %}">Редактировать</a>
    {% endif %}
</div>

{% if images %}
    <div>
        <h2>Дополнительные изображения</h2>
        <div style="display: flex; flex-wrap: wrap;">
            {% for image in images %}
                <div style="margin: 10px;">
                    <img src="{{ image.image.url }}" alt="{{ product.name }}" style="max-width: 200px;">
                </div>
            {% endfor %}
        </div>
    </div>
{% else %}
    <p>Дополнительных изображений нет.</p>
{% endif %}


{% endblock %}

partners/templates/partners/edit_partners.html
{% extends 'reg/base.html' %}

{% block title %}Редактирование партнера{% endblock %}

{% block content %}
    <h1>Редактирование партнёра: {{ partner.name }}</h1>

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}

        <!-- Основная форма -->
        <div>
            {{ form.as_p }}
        </div>

        <!-- Форма для дополнительных изображений -->
        <h2>Дополнительные изображения</h2>
        {{ formset.management_form }}
        {% for image_form in formset %}
            <div>
                {{ image_form.as_p }}
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>

{% endblock %}

partners/templates/partners/partners.html
{% extends 'reg/base.html' %}

{% block title %}Партнеры{% endblock %}

{% block content %}

<body>
    <h1>Партнеры</h1>
    <a href="{% url 'partners:new_partner' %}">Добавить партнера</a>
    <ul class="products">
        {% for i in partners %}
            <li class="product-wrapper">
                <a href="{% url 'partners:info_partner' i.pk %}">
                    <span>
                        {{ i.name }}
                    </span>

                    <div class="product-photo">
                        <img src="{{ i.main_image.url }}" alt="">
                    </div>
                </a>
            </li>
        {% endfor %}
    </ul>
</body>

{% endblock %}