elka/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('reg.urls')),
    path('', include('event.urls')),
    path('feedback/', include('feedback.urls')),
    path('adminchat/', include('adminchat.urls')),
    path('partners/', include('partners.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'event'

urlpatterns = [
    path('', views.actual_events, name='main_page'),
    path('new_event/', views.create_event, name='new_event'),
    path('cart_add/<int:pk>/', views.add_event, name='add_event'),
    path('user_cart/', views.my_user_event, name='user_event'),
    path('admin_cart/', views.my_admin_event, name='admin_event'),
    path('info_event/<int:pk>/', views.info_event, name='info_event'),
    path('all_event/', views.all_event, name='all_event'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('calendar/', views.user_calendar, name='user_calendar'),
    path('edit_event/<int:pk>/', views.edit, name='edit_event')
]

reg/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'reg'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='reg/login.html', authentication_form=LoginForm),
         name='login'),
    path('logout/', views.logout_view, name='logout')
]

event/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User


class Events(models.Model):

    STATUS_CHOISES = [
        ('active', 'Активныне'),
        ('completed', 'Завершенный')
    ]

    title = models.CharField(max_length=32)
    description = models.TextField()
    image = models.ImageField(upload_to='events_images/')
    event_datetime = models.DateTimeField()
    latitude = models.FloatField(default=55.7558)
    longitude = models.FloatField(default=37.6176)
    address = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOISES, default='active')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)


    def __str__(self):
        return self.title


class Myevent(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    event = models.ForeignKey(Events, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user}'

event/forms.py
from .models import Events
from django import forms

class NewItemForm(forms.ModelForm):

    class Meta:
        model = Events
        fields = ['title', 'description', 'image', 'event_datetime', 'status', 'latitude', 'longitude', 'address']
        widgets = {
            'title': forms.TextInput(),
            'description': forms.Textarea(),
            'image': forms.ClearableFileInput(),
            'event_datetime': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'status': forms.Select(),
            'latitude': forms.HiddenInput(),
            'longitude': forms.HiddenInput(),
            'address': forms.HiddenInput(),
        }


class EditItemForm(forms.ModelForm):

    class Meta:
        model = Events
        fields = ['title', 'description', 'image', 'event_datetime', 'status', 'latitude', 'longitude', 'address']
        widgets = {
            'title': forms.TextInput(),
            'description': forms.Textarea(),
            'image': forms.ClearableFileInput(),
            'event_datetime': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'status': forms.Select(),
            'latitude': forms.HiddenInput(),
            'longitude': forms.HiddenInput(),
            'address': forms.HiddenInput(),
        }

event/views.py
from calendar import HTMLCalendar
from django.utils import timezone

from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test

from .models import Events, Myevent
from .forms import NewItemForm, EditItemForm


def actual_events(request):

    new_events = Events.objects.order_by('-event_datetime')[:8]

    return render(request, 'event/main_page.html', {'new_events': new_events})


@user_passes_test(lambda u: u.is_superuser)
def create_event(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.user = request.user
            item.save()

            return redirect('/')

    else:
        form = NewItemForm()

    return render(request, 'event/new.html', context={'form': form})


@user_passes_test(lambda u: u.is_superuser)
def my_admin_event(request):
    events = Events.objects.filter(user=request.user)
    return render(request, 'event/my_admin_events.html', {'events': events})


@login_required
def add_event(request, pk):
    event = get_object_or_404(Events, pk=pk)
    cart_item, created = Myevent.objects.get_or_create(
        user=request.user,
        event=event
    )

    cart_item.save()

    return redirect('/')

@login_required
def my_user_event(request):
    myeve = Myevent.objects.filter(user=request.user)

    return render(request, 'event/my_user_events.html', {
        'Myevents': myeve,
    })


def info_event(request, pk):
    event = get_object_or_404(Events, pk=pk)

    return render(request, 'event/event_detail.html', {'event': event})

def all_event(request):
    query = request.GET.get('query', '')
    event = Events.objects.all()

    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')

    if query:
        event = event.filter(Q(title__icontains=query) | Q(description__icontains=query))

    if start_date and end_date:
        event = event.filter(event_datetime__range=(start_date, end_date))

    paginator = Paginator(event, 4)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'event/all.html', context={'event': event,
                                                       'query': query,
                                                       'page_obj': page_obj})

@user_passes_test(lambda u: u.is_superuser)
def delete(request, pk):
    event = get_object_or_404(Events, pk=pk)
    event.delete()

    return redirect('/')


def user_calendar(request):
    user = request.user  # Текущий пользователь

    # Получаем год и месяц из запроса
    try:
        year = int(request.GET.get('year', timezone.now().year))
        month = int(request.GET.get('month', timezone.now().month))
    except (ValueError, TypeError):
        year = timezone.now().year
        month = timezone.now().month

    # Корректируем год и месяц, если они некорректны
    if month > 12:
        year += 1
        month = 1
    elif month < 1:
        year -= 1
        month = 12

    # Получаем лайкнутые события пользователя
    my_events = Myevent.objects.filter(user=user).select_related('event')

    # Создаём календарь
    cal = HTMLCalendar().formatmonth(year, month)

    # Формируем данные для отображения событий в календаре
    events_dict = {}
    for my_event in my_events:
        event_date = my_event.event.event_datetime.date()  # Дата события
        if event_date not in events_dict:
            events_dict[event_date] = []
        events_dict[event_date].append(my_event.event)

    return render(request, 'event/user_calendar.html', {
        'calendar': cal,
        'events_dict': events_dict,
        'year': year,
        'month': month,
    })


@user_passes_test(lambda u: u.is_superuser)
def edit(request, pk):
    event = get_object_or_404(Events, pk=pk)
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=event)

        if form.is_valid():
            form.save()

            return redirect('event:info_event', pk=event.id)

    else:
        form = EditItemForm(instance=event)

    return render(request, 'event/edit_event.html', context={'form': form})

event/templates/event/all.html
{% extends 'reg/base.html' %}

{% block title %}Все мероприятия{% endblock %}

{% block content %}
<body>
        <div class="searching">
            <form method="get" action="{% url 'event:all_event' %}">
                <input name="query" type="text"
                       value="{{ query }}" placeholder="Название или описание">

                <button>
                    Поиск
                </button>
            </form>

            <div class="dropdown">
                <form method="get" class="filter">
                    <h3><label>Фильрация по датам:</label></h3><p>
                    <label>От</label>
                    <input type="datetime-local" id="start_date" name="start_date"><p>
                    <label>До</label>
                    <input type="datetime-local" id="end_date" name="end_date"><p>
                    <button type="submit">Поиск</button>
                    <button>
                        <a href="{% url 'event:all_event' %}">
                            Сброс
                        </a>
                    </button>
                </form>
            </div>
        </div>

        <div>
            <ul class="products">
            {% for event in page_obj %}
                <li class="product-wrapper">
                    <a href="{% url 'event:info_event' event.pk %}">
                        <div class="product-photo">
                            <img src="{{ event.image.url }}">
                        </div>

                        <span>
                            {{ event.title }}
                        </span>

                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
        

        
            <div class="pagination">
                <span>
                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                </span>
            </div>

            <div>
                {% if page_obj.has_previous %}
                    <a href="?page=1">Первая</a>
                    <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <strong>{{ num }}</strong>
                    {% else %}
                        <a href="?page={{ num }}">{{ num }}</a>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
                {% endif %}
            </div>
</body>
{% endblock %}

event/templates/event/edit_event.html
{% extends 'reg/base.html' %}

{% block title %}Изменить мероприятие{% endblock %}

{% block content %}
    <h1>Изменить мероприятие</h1>

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}

        <div>
            {{form.as_p}}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div>
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button>Submit</button>

    </form>

<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>

<div id="map" style="height: 400px; margin: 20px 0;"></div>

<script>
    const map = L.map('map').setView([55.7558, 37.6176], 10);
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '© OpenStreetMap contributors'
    }).addTo(map);

    let marker;
    let addressField = document.getElementById('id_address');
    let latitudeField = document.getElementById('id_latitude');
    let longitudeField = document.getElementById('id_longitude');

    async function getAddress(lat, lng) {
        const response = await fetch(`https://nominatim.openstreetmap.org/reverse?format=json&lat=${lat}&lon=${lng}`);
        const data = await response.json();
        return data.display_name || "Адрес не найден";
    }

    map.on('click', async function(e) {
        const lat = e.latlng.lat;
        const lng = e.latlng.lng;

        if (marker) {
            map.removeLayer(marker);
        }

        marker = L.marker([lat, lng]).addTo(map);

        latitudeField.value = lat;
        longitudeField.value = lng;

        const address = await getAddress(lat, lng);
        addressField.value = address;
    });
</script>
{% endblock %}

event/templates/event/event_detail.html
{% extends 'reg/base.html' %}

{% block title %}Информация о мероприятии{% endblock %}

{% block content %}

<div>
    <div class="event">
        <div class="left-image">
            <img src="{{ event.image.url }}">
        </div>

        <span>
            {{ event.title }}
            {{ event.description }}
            {{ event.event_datetime }}
            {{ event.status }}
            Создатель: {{ event.user }}
        </span>
    </div>
    <a href="{% url 'event:add_event' event.pk %}">Хочу на это событие</a>
    {% if user.is_superuser %}
    <a href="{% url 'event:delete' event.pk %}">Удалить</a>
    <a href="{% url 'event:edit_event' event.pk %}">Редактировать</a>
    {% endif %}
</div>

<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>


<h2>{{ event.name }}</h2>
<p>Адрес: {{ event.address }}</p>
<div id="map-{{ event.id }}" style="height: 300px; margin: 20px 0;"></div>

<script>
    const map{{ event.id }} = L.map('map-{{ event.id }}').setView([{{ event.latitude }}, {{ event.longitude }}], 13);
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '© OpenStreetMap contributors'
    }).addTo(map{{ event.id }});

    L.marker([{{ event.latitude }}, {{ event.longitude }}])
        .addTo(map{{ event.id }})
        .bindPopup("{{ event.name }}");
</script>

{% endblock %}

event/templates/event/main_page.html
{% extends 'reg/base.html' %}

{% block title %}Главная{% endblock %}

{% block content %}

<body>
    <h1>Новые</h1>
    <ul class="products">
        {% for i in new_events %}
            <li class="product-wrapper">
                <a href="{% url 'event:info_event' i.pk %}">
                    <span>
                        {{ i.title }}
                    </span>

                    <div class="product-photo">
                        <img src="{{ i.image.url }}" alt="">
                    </div>
                </a>
            </li>
        {% endfor %}
    </ul>
</body>

{% endblock %}

event/templates/event/my_admin_events.html
{% extends 'reg/base.html' %}

{% block title %}Мои созданные мероприятия{% endblock %}

{% block content %}

<body>
    <ul class="products">
        {% for i in events %}
            <li class="product-wrapper">
                <a href="{% url 'event:info_event' i.pk %}">
                    <div class="product-photo">
                        <img src="{{ i.image.url }}">
                    </div>

                    <span>
                        {{ i.title }}
                    </span>
                </a>
            </li>
        {% endfor %}
    </ul>
</body>

{% endblock %}

event/templates/event/my_user_events.html
{% extends 'reg/base.html' %}

{% block title %}Мои мероприятия пользователя{% endblock %}

{% block content %}

<body>
    <ul class="products">
        {% for i in Myevents %}
            <li class="product-wrapper">
                <a href="{% url 'event:info_event' i.event.pk %}">
                    <div class="product-photo">
                        <img src="{{ i.event.image.url }}">
                    </div>

                    <span>
                        {{ i.event.title }}
                    </span>

                </a>
            </li>
        {% endfor %}
    </ul>
</body>


{% endblock %}

event/templates/event/new.html
{% extends 'reg/base.html' %}

{% block title %}Новое мероприятие{% endblock %}

{% block content %}
    <h1>Новое мероприятие</h1>

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}

        <div>
            {{form.as_p}}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div>
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button>Submit</button>

    </form>


<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>

<div id="map" style="height: 400px; margin: 20px 0;"></div>

<script>
    const map = L.map('map').setView([55.7558, 37.6176], 10);
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '© OpenStreetMap contributors'
    }).addTo(map);

    let marker;
    let addressField = document.getElementById('id_address');
    let latitudeField = document.getElementById('id_latitude');
    let longitudeField = document.getElementById('id_longitude');

    async function getAddress(lat, lng) {
        const response = await fetch(`https://nominatim.openstreetmap.org/reverse?format=json&lat=${lat}&lon=${lng}`);
        const data = await response.json();
        return data.display_name || "Адрес не найден";
    }

    map.on('click', async function(e) {
        const lat = e.latlng.lat;
        const lng = e.latlng.lng;

        if (marker) {
            map.removeLayer(marker);
        }

        marker = L.marker([lat, lng]).addTo(map);

        latitudeField.value = lat;
        longitudeField.value = lng;

        const address = await getAddress(lat, lng);
        addressField.value = address;
    });
</script>
{% endblock %}

event/templates/event/user_calendar.html
{% extends 'reg/base.html' %}

{% block title %}Календарь мероприятий{% endblock %}

{% block content %}

<body>
    <h1>Календарь событий</h1>
    <div>
        <a href="?year={{ year }}&month={{ month|add:-1 }}">Предыдущий месяц</a>
        <span>{{ year }}-{{ month }}</span>
        <a href="?year={{ year }}&month={{ month|add:1 }}">Следующий месяц</a>
    </div>
    

    <h2>События</h2>
    <ul class="event-list">
        <table class="calendar">
            {{ calendar|safe }}
        </table>
        {% for date, events in events_dict.items %}
            {% if date.year == year and date.month == month %}
                <li>
                    <strong>{{ date }}</strong>
                    <ul>
                        {% for event in events %}
                            <li>{{ event.title }} ({{ event.event_datetime.time }})</li>
                        {% endfor %}
                    </ul>
                </li>
            {% endif %}
        {% endfor %}
    </ul>
</body>
{% endblock %}