adminchat/urls.py
from django.urls import path
from . import views

app_name = 'adminchat'

urlpatterns = [
    path('chat/', views.chat_room, name='chat_room'),
    path('chat/admin/<str:room_name>/', views.chat_room, name='admin_chat_room'),
    path('chat/list/', views.chat_list, name='chat_list'),
]

elka/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('reg.urls')),
    path('', include('event.urls')),
    path('feedback/', include('feedback.urls')),
    path('adminchat/', include('adminchat.urls')),
    path('partners/', include('partners.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'event'

urlpatterns = [
    path('', views.actual_events, name='main_page'),
    path('new_event/', views.create_event, name='new_event'),
    path('cart_add/<int:pk>/', views.add_event, name='add_event'),
    path('user_cart/', views.my_user_event, name='user_event'),
    path('admin_cart/', views.my_admin_event, name='admin_event'),
    path('info_event/<int:pk>/', views.info_event, name='info_event'),
    path('all_event/', views.all_event, name='all_event'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('calendar/', views.user_calendar, name='user_calendar'),
    path('edit_event/<int:pk>/', views.edit, name='edit_event')
]

feedback/urls.py
from django.urls import path
from . import views

app_name = 'feedback'

urlpatterns = [
    path('feedback/', views.feedback, name='feedback'),
    path('feedback_info/', views.feedback_info, name='feedback_info')
]

reg/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'reg'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='reg/login.html', authentication_form=LoginForm),
         name='login'),
    path('logout/', views.logout_view, name='logout')
]

reg/models.py
from django.db import models

# Create your models here.

reg/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Имя',
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Пароль',
    }))



class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Имя',
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Почта',
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Пароль',
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Еще пароль',
    }))

reg/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from .forms import SignupForm


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/auth/login/')
    else:
        form = SignupForm()
    return render(request, 'reg/register.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('/')

reg/templates/reg/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} | Elka</title>
</head>

<div id="wrap">
<header class="header">
    <div class="container">
        <div class="header__inner">
            <img class="logo" src="/static/logo.png" href="{% url 'event:main_page' %}"></a>
            <nav class="menu">
                {% if user.is_superuser %}
                <div class="nav_button">
                    <a href="{% url 'event:admin_event' %}" class="nav_button-link">
                        Мои события
                    </a>
                </div>
                {% else %}
                <div class="nav_button">
                    <a href="{% url 'event:user_event' %}" class="nav_button-link">
                        Мои события
                    </a>
                </div>
                {% endif %}

                <div class="nav_button">
                    <a href="{% url 'event:all_event' %}" class="nav_button-link">
                        Доступные события
                    </a>
                </div>

                {% if not user.is_superuser %}
                <div class="nav_button">
                    <a href="{% url 'event:user_calendar' %}" class="nav_button-link">
                        Календарь
                    </a>
                </div>
                {% endif %}

                {% if user.is_superuser %}
                <div class="nav_button">
                    <a href="{% url 'event:new_event' %}" class="nav_button-link">
                        Новое событие
                    </a>
                </div>
                {% endif %}
            </nav>

            <nav class="auth">
                {% if request.user.is_authenticated %}
                    <div class="login_button">
                        <a href="{% url 'reg:logout' %}" class="login_button">
                            Выйти из аккаунта
                        </a>
                    </div>
                {% else %}
                    <div class="login_button">
                        <a href="{% url 'reg:signup' %}" class="login_button">
                            Регистрация
                        </a>
                    </div>

                    <div class="login_button">
                        <a href="{% url 'reg:login' %}" class="login_button">
                            Вход в аккаунт
                        </a>
                    </div>
                {% endif %}
            </nav>
        </div>
    </div>
</header>

{% block content %}
{% endblock %}

</div>

<footer class="footer">
    <div class="footer-links">
        <a href="{% url 'event:main_page' %}" class="footer-link">О нас</a>
        <a href="/partners" class="footer-link">Партнеры</a>
        {% if not user.is_superuser %}
            <a href="{% url 'feedback:feedback' %}" class="footer-link">Обратная связь</a>
        {% else %}
            <a href="{% url 'feedback:feedback_info' %}" class="footer-link">Обратная связь</a>
        {% endif %}
        {% if not user.is_superuser %}
            <a href="{% url 'adminchat:chat_room' %}" class="footer-link">Поддержка</a>
        {% else %}
            <a href="{% url 'adminchat:chat_list' %}" class="footer-link">Поддержка</a>
        {% endif %}
    </div>
    <p class="footer-text">Контакты: example@example.com | +7 (123) 456-78-90</p>
    <p class="footer-text">&copy; <span class="footer-year">2025</span></p>
</footer>

reg/templates/reg/login.html
{% extends 'reg/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}

<div class="form">
    <form method="post" action="." class="form">
        {% csrf_token %}
        {{ form.non_field_errors }}

            <div>
                <label>Username</label><br>
                {{ form.username }}
            </div>

            <div>
                <label>Password</label><br>
                {{ form.password }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div>
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button>Submit</button>
    </form>
</div>

{% endblock %}

reg/templates/reg/register.html
{% extends 'reg/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}

<div class="form">
    <form method="post" action="." class="form">
        {% csrf_token %}

        {{ form.non_field_errors }}

        <div class="enter">
            <label>Username</label><br>
            {{ form.username }}
        </div>

        <div class="enter">
            <label>Email</label><br>
            {{ form.email }}
        </div>

        <div class="enter">
            <label>Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="enter">
            <label>Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="enter">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button>Submit</button>
    </form>
</div>

{% endblock %}